#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline, for Wasm
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.3.0
    with:
      extension_name: iceberg
      duckdb_version: v1.3.0
      ci_tools_version: v1.3.0
      exclude_archs: 'windows_amd64;windows_amd64_mingw;linux_amd64_musl;linux_amd64_musl;linux_amd64;linux_amd64;osx_arm64;osx_amd64'
      extra_toolchains: 'python3'

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@v1.3.0
    secrets: inherit
    with:
      extension_name: iceberg
      duckdb_version: v1.3.0
      ci_tools_version: v1.3.0
      exclude_archs: 'windows_amd64;windows_amd64_mingw;linux_amd64_musl;linux_amd64_musl;linux_amd64;linux_amd64;osx_arm64;osx_amd64'
      deploy_latest: 'true'
